name: Publish foret-core to NPM

on:
  push:
    tags:
      - v*-core

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: "@altenull"

      - name: install dependencies
        working-directory: ./foret-core
        run: npm install

      - name: build
        working-directory: ./foret-core
        run: npm run build

      - name: npm ci
        working-directory: ./foret-core
        run: npm ci

      - name: npm publish
        working-directory: ./foret-core
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
